// Generated by scripts/sync-docs-navigation.mjs. Do not edit directly.
const sidebars = {
  "userGuideSidebar": [
    {
      "type": "doc",
      "id": "index",
      "label": "User guide"
    },
    {
      "type": "category",
      "label": "MetaTables",
      "link": {
        "type": "doc",
        "id": "metatables/index"
      },
      "items": [
        {
          "type": "category",
          "label": "Catalog",
          "link": {
            "type": "doc",
            "id": "metatables/catalog/index"
          },
          "items": [
            {
              "type": "category",
              "label": "Data Sources",
              "link": {
                "type": "doc",
                "id": "metatables/catalog/data-sources/index"
              },
              "items": [
                {
                  "type": "doc",
                  "id": "metatables/catalog/data-sources/add-data-source",
                  "label": "Add a Data Source"
                },
                {
                  "type": "doc",
                  "id": "metatables/catalog/data-sources/query-data-source",
                  "label": "Query a Data Source"
                },
                {
                  "type": "doc",
                  "id": "metatables/catalog/data-sources/import-tables",
                  "label": "Import existing tables"
                }
              ]
            },
            {
              "type": "category",
              "label": "MetaTables",
              "link": {
                "type": "doc",
                "id": "metatables/catalog/tables/index"
              },
              "items": [
                {
                  "type": "doc",
                  "id": "metatables/catalog/tables/share-table",
                  "label": "Share a table"
                }
              ]
            },
            {
              "type": "doc",
              "id": "metatables/catalog/time-index-meta-tables/index",
              "label": "Time Index MetaTables"
            },
            {
              "type": "doc",
              "id": "metatables/catalog/data-updates/index",
              "label": "Time Index Table Updates"
            },
            {
              "type": "doc",
              "id": "metatables/catalog/namespaces/index",
              "label": "Namespaces"
            }
          ]
        },
        {
          "type": "category",
          "label": "Monitoring",
          "link": {
            "type": "doc",
            "id": "metatables/monitoring/index"
          },
          "items": [
            {
              "type": "category",
              "label": "Runs",
              "link": {
                "type": "doc",
                "id": "metatables/monitoring/runs/index"
              },
              "items": [
                {
                  "type": "doc",
                  "id": "metatables/monitoring/runs/inspect-run",
                  "label": "Investigate a run"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "type": "category",
      "label": "Admin",
      "link": {
        "type": "doc",
        "id": "admin/index"
      },
      "items": [
        {
          "type": "category",
          "label": "Admin",
          "link": {
            "type": "doc",
            "id": "admin/administration/index"
          },
          "items": [
            {
              "type": "doc",
              "id": "admin/administration/security/index",
              "label": "Security"
            },
            {
              "type": "category",
              "label": "Settings",
              "link": {
                "type": "doc",
                "id": "admin/administration/settings/index"
              },
              "items": [
                {
                  "type": "doc",
                  "id": "admin/administration/settings/select-data-source",
                  "label": "Select a runtime Data Source"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};

export default sidebars;
